### ISSUE TITLE
Issues with init_*() functions with small or large values

### ISSUE THREAD

**Issue by ahazel** [tsahota/NMproject#21]
Hi,

When using the `init_theta()`, `init_omega()`, and `init_sigma()` functions to set values (init, lower, or upper) with numbers that get converted to scientific notation by default (eg 0.0001 -> 1e-4 or 100000 -> 1e5), the value in the table (from `m %>% init_theta() %>% dplyr::first()`) gets set to NA instead. And in the case of `init_theta()`, that row for which the value was set to NA is deleted entirely.

This was tested with the ADVAN2.mod file used in the demo. Additional info provided below.

Thanks,
Anthony

> sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] localanalysis_0.0.0.9000 NMproject_0.6.7          rprojroot_2.0.2          knitr_1.37              

loaded via a namespace (and not attached):
 [1] pillar_1.6.4      compiler_4.1.1    bslib_0.2.5.1     jquerylib_0.1.4   prettyunits_1.1.1 remotes_2.4.0    
 [7] tools_4.1.1       testthat_3.0.4    digest_0.6.27     pkgbuild_1.2.0    pkgload_1.2.1     tibble_3.1.6     
[13] jsonlite_1.7.2    evaluate_0.14     memoise_2.0.0     lifecycle_1.0.1   pkgconfig_2.0.3   rlang_0.4.11     
[19] DBI_1.1.1         rstudioapi_0.13   cli_3.0.1         yaml_2.2.1        xfun_0.29         fastmap_1.1.0    
[25] dplyr_1.0.7       withr_2.4.3       stringr_1.4.0     generics_0.1.1    vctrs_0.3.8       desc_1.3.0       
[31] fs_1.5.0          sass_0.4.0        devtools_2.4.2    tidyselect_1.1.1  glue_1.4.2        R6_2.5.1         
[37] processx_3.5.2    fansi_1.0.2       rmarkdown_2.11    sessioninfo_1.1.1 callr_3.7.0       purrr_0.3.4      
[43] magrittr_2.0.1    ps_1.6.0          ellipsis_0.3.2    htmltools_0.5.2   usethis_2.0.1     assertthat_0.2.1 
[49] utf8_1.2.2        stringi_1.7.6     cachem_1.0.5      crayon_1.4.2

**Comment by tsahota** [comment]
Hi Anthony,

Apologies for the slow response, I've tried reproducing the steps you've described, but I'm having trouble replicating the error. 
 Can you see below if I'm following what you did correctly:

``` r
setwd("C:/Users/tsaho/Documents/projects/test_init")
library(NMproject)

## demo code
m1 <- new_nm(run_id = "m1",
             based_on = "staging/Models/ADVAN2.mod",
             data_path = "DerivedData/data.csv") %>%
  cmd("execute {ctl_name} -dir={run_dir}") %>%
  fill_input() %>%
  init_theta(init = c(0.5, -2.5, -0.5)) %>%  ## initials set for demo
  init_sigma(init = c(0.1, 0.1)) #%>%        ## initials set for demo
  #run_nm()

## rescale KA to be untransformed and scaled downwards 1E7 fold, so it needs a
## big THETA initial estimate
m1 <- m1 %>%
  gsub_ctl("EXP\\(THETA\\(1\\)\\)", 
           "THETA(1) / 1E7")

m1 %>% dollar("PK") ## check $PK
#> $`execute.Models/m1`
#>   1| $PK
#>   2| 
#>   3| TVKA=THETA(1) / 1E7
#>   4| MU_1=LOG(TVKA)
#>   5| KA = EXP(MU_1+ETA(1))
#>   6| 
#>   7| TVK=EXP(THETA(2))
#>   8| MU_2=LOG(TVK)
#>   9| K = EXP(MU_2+ETA(2))
#>  10| 
#>  11| TVV=EXP(THETA(3))
#>  12| MU_3=LOG(TVV)
#>  13| V = EXP(MU_3+ETA(3))
#>  14| 
#>  15| CL = K*V
#>  16| 
#>  17| S2 = V
#>  18|

## Following steps anthony described to reproduce error
it <- m1 %>% init_theta() %>% dplyr::first()  

it$init[it$name == "KA"] <- 1e7

it
#>   name parameter lower     init upper theta   FIX unit trans line pos orig_line
#> 2   KA    THETA1    NA  1.0e+07    NA     1 FALSE  h-1   LOG    2   1         2
#> 3    K    THETA2    NA -2.5e+00    NA     2 FALSE  h-1   LOG    3   1         3
#> 4    V    THETA3    NA -5.0e-01    NA     3 FALSE    L   LOG    4   1         4

m1 <- m1 %>% init_theta(it)

m1 %>% dollar("THETA")
#> $`execute.Models/m1`
#>   1| $THETA
#>   2| 1e+07   ; KA ; h-1 ; LOG
#>   3| -2.5   ; K ; h-1 ; LOG
#>   4| -0.5   ; V ; L ; LOG
```

<sup>Created on 2022-02-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ahazel** [comment]
Hi,

Thank you for the response.

After changing the initial thetas using the `init_theta(it)` approach above, then running `init_theta()` on its own, the bug appears:

``` r
setwd("~/NMproject/test init functions")
library(NMproject)
#> Warning: package 'NMproject' was built under R version 4.1.2

## demo model
m0 = new_nm(run_id = "m0",
            based_on = "staging/Models/ADVAN2.mod",
            data_path = "DerivedData/data.csv") %>%
  cmd("C:\\PsN-5.2.6\\strawberry\\perl\\bin\\execute {ctl_name} -dir={run_dir}") %>%
  fill_input() %>%
  init_theta(init = c(0.5, -2.5, -0.5)) %>%
  init_sigma(init = c(0.1, 0.1))

m0 %>% dollar("THETA")
#> $`execute.Models/m0`
#>   1| $THETA
#>   2| 0.5   ; KA ; h-1 ; LOG
#>   3| -2.5   ; K ; h-1 ; LOG
#>   4| -0.5   ; V ; L ; LOG

it0 = m0 %>% init_theta() %>% dplyr::first()
it0
#>   name parameter lower init upper theta   FIX unit trans line pos orig_line
#> 2   KA    THETA1    NA  0.5    NA     1 FALSE  h-1   LOG    2   1         2
#> 3    K    THETA2    NA -2.5    NA     2 FALSE  h-1   LOG    3   1         3
#> 4    V    THETA3    NA -0.5    NA     3 FALSE    L   LOG    4   1         4


## change init value directly
m1 = m0 %>%
  child(run_id = "m1") %>%
  init_theta(init = c("KA" = 0.000001))

## $THETA output is correct
m1 %>% dollar("THETA")
#> $`execute.Models/m1`
#>   1| $THETA
#>   2| 1e-06   ; KA ; h-1 ; LOG
#>   3| -2.5   ; K ; h-1 ; LOG
#>   4| -0.5   ; V ; L ; LOG

# but KA is missing in stored table!
m1 %>% init_theta() %>% dplyr::first()
#>   name parameter lower init upper theta   FIX unit trans line pos orig_line
#> 3    K    THETA1    NA -2.5    NA     1 FALSE  h-1   LOG    3   1         3
#> 4    V    THETA2    NA -0.5    NA     2 FALSE    L   LOG    4   1         4


## change value in table first, then use table
## same result as above
it2 = it0
it2$init[it2$name == "KA"] = 0.000001
## this table is correct
it2
#>   name parameter lower     init upper theta   FIX unit trans line pos orig_line
#> 2   KA    THETA1    NA  1.0e-06    NA     1 FALSE  h-1   LOG    2   1         2
#> 3    K    THETA2    NA -2.5e+00    NA     2 FALSE  h-1   LOG    3   1         3
#> 4    V    THETA3    NA -5.0e-01    NA     3 FALSE    L   LOG    4   1         4

m2 = m0 %>%
  child(run_id = "m2") %>%
  init_theta(it2)

## $THETA output is correct
m2 %>% dollar("THETA")
#> $`execute.Models/m2`
#>   1| $THETA
#>   2| 1e-06   ; KA ; h-1 ; LOG
#>   3| -2.5   ; K ; h-1 ; LOG
#>   4| -0.5   ; V ; L ; LOG

## this table is missing KA
m2 %>% init_theta() %>% dplyr::first()
#>   name parameter lower init upper theta   FIX unit trans line pos orig_line
#> 3    K    THETA1    NA -2.5    NA     1 FALSE  h-1   LOG    3   1         3
#> 4    V    THETA2    NA -0.5    NA     2 FALSE    L   LOG    4   1         4

## try to use model above as parent model with now missing KA value
## produces error
m3 = m2 %>%
  child(run_id = "m3") %>%
  init_theta(init = c("KA" = 1))
#> Error: parameter name not found, must be one of the following:
#>  K, V
```

<sup>Created on 2022-02-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

So, while the `dollar("THETA")` output is correct, the stored parameter is missing, meaning the model can no longer be used as a parent model going forward.

Best,

Anthony

**Comment by tsahota** [comment]
Very clear, that helped me track down the bug, thanks.  I've put the fix into the development version for the next release.  I'll be making a CRAN release in a few weeks, but until then installing the github version (`install_github("tsahota/NMproject")`) should resolve the issue.

If you don't want all the updates though let me know and I can make a hot fix for you containing just this change for you to install.

**Comment by ahazel** [comment]
Thank you for the update.

I'm using the latest github version now, and while the `init_theta()` issue is now fixed, the same issue is still occurring for `init_omega()` and `init_sigma()`.

Best,

Anthony

**Comment by tsahota** [comment]
Apologies I should have spotted that!  Included fix
